export interface CountryCode {
  code: string
  country: string
  iso: string
  flag: string
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: "+93",  iso: "AF", flag: "🇦🇫", country: "Afghanistan" },
  { code: "+355", iso: "AL", flag: "🇦🇱", country: "Albania" },
  { code: "+213", iso: "DZ", flag: "🇩🇿", country: "Algeria" },
  { code: "+376", iso: "AD", flag: "🇦🇩", country: "Andorra" },
  { code: "+244", iso: "AO", flag: "🇦🇴", country: "Angola" },
  { code: "+54",  iso: "AR", flag: "🇦🇷", country: "Argentina" },
  { code: "+374", iso: "AM", flag: "🇦🇲", country: "Armenia" },
  { code: "+61",  iso: "AU", flag: "🇦🇺", country: "Australia" },
  { code: "+43",  iso: "AT", flag: "🇦🇹", country: "Austria" },
  { code: "+994", iso: "AZ", flag: "🇦🇿", country: "Azerbaijan" },
  { code: "+1242",iso: "BS", flag: "🇧🇸", country: "Bahamas" },
  { code: "+973", iso: "BH", flag: "🇧🇭", country: "Bahrain" },
  { code: "+880", iso: "BD", flag: "🇧🇩", country: "Bangladesh" },
  { code: "+375", iso: "BY", flag: "🇧🇾", country: "Belarus" },
  { code: "+32",  iso: "BE", flag: "🇧🇪", country: "Belgium" },
  { code: "+501", iso: "BZ", flag: "🇧🇿", country: "Belize" },
  { code: "+229", iso: "BJ", flag: "🇧🇯", country: "Benin" },
  { code: "+975", iso: "BT", flag: "🇧🇹", country: "Bhutan" },
  { code: "+591", iso: "BO", flag: "🇧🇴", country: "Bolivia" },
  { code: "+387", iso: "BA", flag: "🇧🇦", country: "Bosnia and Herzegovina" },
  { code: "+267", iso: "BW", flag: "🇧🇼", country: "Botswana" },
  { code: "+55",  iso: "BR", flag: "🇧🇷", country: "Brazil" },
  { code: "+673", iso: "BN", flag: "🇧🇳", country: "Brunei" },
  { code: "+359", iso: "BG", flag: "🇧🇬", country: "Bulgaria" },
  { code: "+226", iso: "BF", flag: "🇧🇫", country: "Burkina Faso" },
  { code: "+257", iso: "BI", flag: "🇧🇮", country: "Burundi" },
  { code: "+855", iso: "KH", flag: "🇰🇭", country: "Cambodia" },
  { code: "+237", iso: "CM", flag: "🇨🇲", country: "Cameroon" },
  { code: "+1",   iso: "CA", flag: "🇨🇦", country: "Canada" },
  { code: "+238", iso: "CV", flag: "🇨🇻", country: "Cape Verde" },
  { code: "+236", iso: "CF", flag: "🇨🇫", country: "Central African Republic" },
  { code: "+235", iso: "TD", flag: "🇹🇩", country: "Chad" },
  { code: "+56",  iso: "CL", flag: "🇨🇱", country: "Chile" },
  { code: "+86",  iso: "CN", flag: "🇨🇳", country: "China" },
  { code: "+57",  iso: "CO", flag: "🇨🇴", country: "Colombia" },
  { code: "+269", iso: "KM", flag: "🇰🇲", country: "Comoros" },
  { code: "+242", iso: "CG", flag: "🇨🇬", country: "Congo" },
  { code: "+243", iso: "CD", flag: "🇨🇩", country: "Congo (DRC)" },
  { code: "+506", iso: "CR", flag: "🇨🇷", country: "Costa Rica" },
  { code: "+385", iso: "HR", flag: "🇭🇷", country: "Croatia" },
  { code: "+53",  iso: "CU", flag: "🇨🇺", country: "Cuba" },
  { code: "+357", iso: "CY", flag: "🇨🇾", country: "Cyprus" },
  { code: "+420", iso: "CZ", flag: "🇨🇿", country: "Czech Republic" },
  { code: "+45",  iso: "DK", flag: "🇩🇰", country: "Denmark" },
  { code: "+253", iso: "DJ", flag: "🇩🇯", country: "Djibouti" },
  { code: "+1809",iso: "DO", flag: "🇩🇴", country: "Dominican Republic" },
  { code: "+593", iso: "EC", flag: "🇪🇨", country: "Ecuador" },
  { code: "+20",  iso: "EG", flag: "🇪🇬", country: "Egypt" },
  { code: "+503", iso: "SV", flag: "🇸🇻", country: "El Salvador" },
  { code: "+240", iso: "GQ", flag: "🇬🇶", country: "Equatorial Guinea" },
  { code: "+291", iso: "ER", flag: "🇪🇷", country: "Eritrea" },
  { code: "+372", iso: "EE", flag: "🇪🇪", country: "Estonia" },
  { code: "+251", iso: "ET", flag: "🇪🇹", country: "Ethiopia" },
  { code: "+679", iso: "FJ", flag: "🇫🇯", country: "Fiji" },
  { code: "+358", iso: "FI", flag: "🇫🇮", country: "Finland" },
  { code: "+33",  iso: "FR", flag: "🇫🇷", country: "France" },
  { code: "+241", iso: "GA", flag: "🇬🇦", country: "Gabon" },
  { code: "+220", iso: "GM", flag: "🇬🇲", country: "Gambia" },
  { code: "+995", iso: "GE", flag: "🇬🇪", country: "Georgia" },
  { code: "+49",  iso: "DE", flag: "🇩🇪", country: "Germany" },
  { code: "+233", iso: "GH", flag: "🇬🇭", country: "Ghana" },
  { code: "+30",  iso: "GR", flag: "🇬🇷", country: "Greece" },
  { code: "+502", iso: "GT", flag: "🇬🇹", country: "Guatemala" },
  { code: "+224", iso: "GN", flag: "🇬🇳", country: "Guinea" },
  { code: "+245", iso: "GW", flag: "🇬🇼", country: "Guinea-Bissau" },
  { code: "+592", iso: "GY", flag: "🇬🇾", country: "Guyana" },
  { code: "+509", iso: "HT", flag: "🇭🇹", country: "Haiti" },
  { code: "+504", iso: "HN", flag: "🇭🇳", country: "Honduras" },
  { code: "+36",  iso: "HU", flag: "🇭🇺", country: "Hungary" },
  { code: "+354", iso: "IS", flag: "🇮🇸", country: "Iceland" },
  { code: "+91",  iso: "IN", flag: "🇮🇳", country: "India" },
  { code: "+62",  iso: "ID", flag: "🇮🇩", country: "Indonesia" },
  { code: "+98",  iso: "IR", flag: "🇮🇷", country: "Iran" },
  { code: "+964", iso: "IQ", flag: "🇮🇶", country: "Iraq" },
  { code: "+353", iso: "IE", flag: "🇮🇪", country: "Ireland" },
  { code: "+972", iso: "IL", flag: "🇮🇱", country: "Israel" },
  { code: "+39",  iso: "IT", flag: "🇮🇹", country: "Italy" },
  { code: "+1876",iso: "JM", flag: "🇯🇲", country: "Jamaica" },
  { code: "+81",  iso: "JP", flag: "🇯🇵", country: "Japan" },
  { code: "+962", iso: "JO", flag: "🇯🇴", country: "Jordan" },
  { code: "+7",   iso: "KZ", flag: "🇰🇿", country: "Kazakhstan" },
  { code: "+254", iso: "KE", flag: "🇰🇪", country: "Kenya" },
  { code: "+686", iso: "KI", flag: "🇰🇮", country: "Kiribati" },
  { code: "+965", iso: "KW", flag: "🇰🇼", country: "Kuwait" },
  { code: "+996", iso: "KG", flag: "🇰🇬", country: "Kyrgyzstan" },
  { code: "+856", iso: "LA", flag: "🇱🇦", country: "Laos" },
  { code: "+371", iso: "LV", flag: "🇱🇻", country: "Latvia" },
  { code: "+961", iso: "LB", flag: "🇱🇧", country: "Lebanon" },
  { code: "+266", iso: "LS", flag: "🇱🇸", country: "Lesotho" },
  { code: "+231", iso: "LR", flag: "🇱🇷", country: "Liberia" },
  { code: "+218", iso: "LY", flag: "🇱🇾", country: "Libya" },
  { code: "+423", iso: "LI", flag: "🇱🇮", country: "Liechtenstein" },
  { code: "+370", iso: "LT", flag: "🇱🇹", country: "Lithuania" },
  { code: "+352", iso: "LU", flag: "🇱🇺", country: "Luxembourg" },
  { code: "+261", iso: "MG", flag: "🇲🇬", country: "Madagascar" },
  { code: "+265", iso: "MW", flag: "🇲🇼", country: "Malawi" },
  { code: "+60",  iso: "MY", flag: "🇲🇾", country: "Malaysia" },
  { code: "+960", iso: "MV", flag: "🇲🇻", country: "Maldives" },
  { code: "+223", iso: "ML", flag: "🇲🇱", country: "Mali" },
  { code: "+356", iso: "MT", flag: "🇲🇹", country: "Malta" },
  { code: "+222", iso: "MR", flag: "🇲🇷", country: "Mauritania" },
  { code: "+230", iso: "MU", flag: "🇲🇺", country: "Mauritius" },
  { code: "+52",  iso: "MX", flag: "🇲🇽", country: "Mexico" },
  { code: "+691", iso: "FM", flag: "🇫🇲", country: "Micronesia" },
  { code: "+373", iso: "MD", flag: "🇲🇩", country: "Moldova" },
  { code: "+377", iso: "MC", flag: "🇲🇨", country: "Monaco" },
  { code: "+976", iso: "MN", flag: "🇲🇳", country: "Mongolia" },
  { code: "+382", iso: "ME", flag: "🇲🇪", country: "Montenegro" },
  { code: "+212", iso: "MA", flag: "🇲🇦", country: "Morocco" },
  { code: "+258", iso: "MZ", flag: "🇲🇿", country: "Mozambique" },
  { code: "+95",  iso: "MM", flag: "🇲🇲", country: "Myanmar" },
  { code: "+264", iso: "NA", flag: "🇳🇦", country: "Namibia" },
  { code: "+674", iso: "NR", flag: "🇳🇷", country: "Nauru" },
  { code: "+977", iso: "NP", flag: "🇳🇵", country: "Nepal" },
  { code: "+31",  iso: "NL", flag: "🇳🇱", country: "Netherlands" },
  { code: "+64",  iso: "NZ", flag: "🇳🇿", country: "New Zealand" },
  { code: "+505", iso: "NI", flag: "🇳🇮", country: "Nicaragua" },
  { code: "+227", iso: "NE", flag: "🇳🇪", country: "Niger" },
  { code: "+234", iso: "NG", flag: "🇳🇬", country: "Nigeria" },
  { code: "+850", iso: "KP", flag: "🇰🇵", country: "North Korea" },
  { code: "+389", iso: "MK", flag: "🇲🇰", country: "North Macedonia" },
  { code: "+47",  iso: "NO", flag: "🇳🇴", country: "Norway" },
  { code: "+968", iso: "OM", flag: "🇴🇲", country: "Oman" },
  { code: "+92",  iso: "PK", flag: "🇵🇰", country: "Pakistan" },
  { code: "+680", iso: "PW", flag: "🇵🇼", country: "Palau" },
  { code: "+507", iso: "PA", flag: "🇵🇦", country: "Panama" },
  { code: "+675", iso: "PG", flag: "🇵🇬", country: "Papua New Guinea" },
  { code: "+595", iso: "PY", flag: "🇵🇾", country: "Paraguay" },
  { code: "+51",  iso: "PE", flag: "🇵🇪", country: "Peru" },
  { code: "+63",  iso: "PH", flag: "🇵🇭", country: "Philippines" },
  { code: "+48",  iso: "PL", flag: "🇵🇱", country: "Poland" },
  { code: "+351", iso: "PT", flag: "🇵🇹", country: "Portugal" },
  { code: "+974", iso: "QA", flag: "🇶🇦", country: "Qatar" },
  { code: "+40",  iso: "RO", flag: "🇷🇴", country: "Romania" },
  { code: "+7",   iso: "RU", flag: "🇷🇺", country: "Russia" },
  { code: "+250", iso: "RW", flag: "🇷🇼", country: "Rwanda" },
  { code: "+685", iso: "WS", flag: "🇼🇸", country: "Samoa" },
  { code: "+378", iso: "SM", flag: "🇸🇲", country: "San Marino" },
  { code: "+239", iso: "ST", flag: "🇸🇹", country: "São Tomé and Príncipe" },
  { code: "+966", iso: "SA", flag: "🇸🇦", country: "Saudi Arabia" },
  { code: "+221", iso: "SN", flag: "🇸🇳", country: "Senegal" },
  { code: "+381", iso: "RS", flag: "🇷🇸", country: "Serbia" },
  { code: "+248", iso: "SC", flag: "🇸🇨", country: "Seychelles" },
  { code: "+232", iso: "SL", flag: "🇸🇱", country: "Sierra Leone" },
  { code: "+65",  iso: "SG", flag: "🇸🇬", country: "Singapore" },
  { code: "+421", iso: "SK", flag: "🇸🇰", country: "Slovakia" },
  { code: "+386", iso: "SI", flag: "🇸🇮", country: "Slovenia" },
  { code: "+677", iso: "SB", flag: "🇸🇧", country: "Solomon Islands" },
  { code: "+252", iso: "SO", flag: "🇸🇴", country: "Somalia" },
  { code: "+27",  iso: "ZA", flag: "🇿🇦", country: "South Africa" },
  { code: "+82",  iso: "KR", flag: "🇰🇷", country: "South Korea" },
  { code: "+211", iso: "SS", flag: "🇸🇸", country: "South Sudan" },
  { code: "+34",  iso: "ES", flag: "🇪🇸", country: "Spain" },
  { code: "+94",  iso: "LK", flag: "🇱🇰", country: "Sri Lanka" },
  { code: "+249", iso: "SD", flag: "🇸🇩", country: "Sudan" },
  { code: "+597", iso: "SR", flag: "🇸🇷", country: "Suriname" },
  { code: "+268", iso: "SZ", flag: "🇸🇿", country: "Eswatini" },
  { code: "+46",  iso: "SE", flag: "🇸🇪", country: "Sweden" },
  { code: "+41",  iso: "CH", flag: "🇨🇭", country: "Switzerland" },
  { code: "+963", iso: "SY", flag: "🇸🇾", country: "Syria" },
  { code: "+886", iso: "TW", flag: "🇹🇼", country: "Taiwan" },
  { code: "+992", iso: "TJ", flag: "🇹🇯", country: "Tajikistan" },
  { code: "+255", iso: "TZ", flag: "🇹🇿", country: "Tanzania" },
  { code: "+66",  iso: "TH", flag: "🇹🇭", country: "Thailand" },
  { code: "+228", iso: "TG", flag: "🇹🇬", country: "Togo" },
  { code: "+676", iso: "TO", flag: "🇹🇴", country: "Tonga" },
  { code: "+1868",iso: "TT", flag: "🇹🇹", country: "Trinidad and Tobago" },
  { code: "+216", iso: "TN", flag: "🇹🇳", country: "Tunisia" },
  { code: "+90",  iso: "TR", flag: "🇹🇷", country: "Turkey" },
  { code: "+993", iso: "TM", flag: "🇹🇲", country: "Turkmenistan" },
  { code: "+688", iso: "TV", flag: "🇹🇻", country: "Tuvalu" },
  { code: "+256", iso: "UG", flag: "🇺🇬", country: "Uganda" },
  { code: "+380", iso: "UA", flag: "🇺🇦", country: "Ukraine" },
  { code: "+971", iso: "AE", flag: "🇦🇪", country: "United Arab Emirates" },
  { code: "+44",  iso: "GB", flag: "🇬🇧", country: "United Kingdom" },
  { code: "+1",   iso: "US", flag: "🇺🇸", country: "United States" },
  { code: "+598", iso: "UY", flag: "🇺🇾", country: "Uruguay" },
  { code: "+998", iso: "UZ", flag: "🇺🇿", country: "Uzbekistan" },
  { code: "+678", iso: "VU", flag: "🇻🇺", country: "Vanuatu" },
  { code: "+379", iso: "VA", flag: "🇻🇦", country: "Vatican City" },
  { code: "+58",  iso: "VE", flag: "🇻🇪", country: "Venezuela" },
  { code: "+84",  iso: "VN", flag: "🇻🇳", country: "Vietnam" },
  { code: "+967", iso: "YE", flag: "🇾🇪", country: "Yemen" },
  { code: "+260", iso: "ZM", flag: "🇿🇲", country: "Zambia" },
  { code: "+263", iso: "ZW", flag: "🇿🇼", country: "Zimbabwe" },
]
